import { Package, CheckCircle, AlertTriangle, Ban, FileText, Clock, Star } from 'lucide-react';

export const CURRENT_USER = {
  id: 'USR-ADMIN',
  name: 'Nguyễn Văn An',
  email: 'an.nguyen@gmail.com',
  phone: '0912 345 678',
  job: 'Kỹ sư Phần mềm',
  address: 'Hai Bà Trưng, Hà Nội',
  joinDate: 'Tháng 9, 2023',
  verified: true,
  twoFA: true,
  avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=NVA&backgroundColor=1e6b6b&textColor=ffffff',
  stats: [
    { label: 'Tin đã đăng', value: '12', sub: 'tổng cộng', icon: FileText },
    { label: 'Đã trao trả', value: '7', sub: 'thành công', icon: CheckCircle },
    { label: 'Đang xử lý', value: '3', sub: 'chờ xác minh', icon: Clock },
    { label: 'Điểm uy tín', value: '4.9', sub: '/ 5.0', icon: Star },
  ],
};

export const MOCK_STATS = [
  { id: 1, title: 'Tổng tin đăng', value: '1,842', change: '+12.5%', isUp: true, icon: Package, color: 'var(--teal-600)', bg: 'rgba(30,107,107,0.1)' },
  { id: 2, title: 'Đã trao trả thành công', value: '1,420', change: '+18.2%', isUp: true, icon: CheckCircle, color: '#10b981', bg: 'rgba(16,185,129,0.1)' },
  { id: 3, title: 'Báo cáo vi phạm', value: '15', change: '5 ca khẩn', isUp: false, icon: AlertTriangle, color: '#ef4444', bg: 'rgba(239,68,68,0.1)' },
  { id: 4, title: 'Tài khoản bị khóa', value: '24', change: '+2 tuần này', isUp: false, icon: Ban, color: '#dc2626', bg: 'rgba(220,38,38,0.1)' },
];

export const INITIAL_ITEMS = [
  {
    id: 'TD-9021',
    title: 'Ví da nam Pedro & CCCD',
    type: 'lost',
    category: 'Giấy tờ & Ví',
    reporter: 'Trần Văn Bình',
    reporterPhone: '0912 345 456',
    location: 'Bãi xe H1, ĐH Bách Khoa Hà Nội',
    date: '10 phút trước',
    status: 'active', 
    aiScore: 98,
    img: 'https://images.unsplash.com/photo-1627123424574-724758594913?w=300&q=80',
    desc: 'Bên trong có 1 thẻ CCCD mang tên Trần Văn Bình, 2 thẻ ngân hàng Techcombank và tiền mặt.',
  },
  {
    id: 'TD-9020',
    title: 'MacBook Pro M2 Space Gray 14"',
    type: 'found',
    category: 'Thiết bị điện tử',
    reporter: 'Lê Minh Cường',
    reporterPhone: '0988 567 112',
    location: 'Bàn số 42 tầng 3 Thư viện Tạ Quang Bửu',
    date: '35 phút trước',
    status: 'matched',
    aiScore: 99,
    img: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=300&q=80',
    desc: 'Nhặt được ở bàn 42, máy có dán sticker Github ở mặt lưng. Đã bàn giao quầy thủ thư.',
  },
  {
    id: 'TD-9019',
    title: 'Chìa khóa smartkey Honda SH',
    type: 'found',
    category: 'Chìa khóa',
    reporter: 'Bác Nguyễn Thành (Bảo vệ)',
    reporterPhone: '0903 234 789',
    location: 'Sảnh tòa Landmark 81, TP.HCM',
    date: '1 giờ trước',
    status: 'active',
    aiScore: null,
    img: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=300&q=80',
    desc: 'Có móc khóa hình gấu bông màu nâu, chìa 3 nút điều khiển.',
  },
  {
    id: 'TD-9018',
    title: 'Điện thoại iPhone 15 Pro Titan',
    type: 'lost',
    category: 'Thiết bị điện tử',
    reporter: 'Phạm Thu Trang',
    reporterPhone: '0977 888 654',
    location: 'Tuyến Bus 32 (Nguyễn Trãi - Cầu Giấy)',
    date: '2 giờ trước',
    status: 'active',
    aiScore: 95,
    img: 'https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=300&q=80',
    desc: 'Ốp lưng trong suốt có dán ảnh polaroid, màn hình có mật khẩu 6 số.',
  },
];

export const INITIAL_REPORTS = [
  {
    id: 'REP-701',
    claimId: 'YC-401',
    itemId: 'TD-9020',
    itemName: 'MacBook Pro M2 Space Gray 14"',
    itemImg: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=300&q=80',
    reportType: 'fraud_claim',
    typeLabel: 'Nghi vấn mạo nhận',
    severity: 'high',
    reporter: 'Lê Minh Cường (Người nhặt được)',
    reportedUser: 'Hoàng Văn X (Tài khoản nghi vấn)',
    reportedUserPhone: '0933 444 888',
    reportedUserId: 'USR-882',
    reason: 'Người này liên tục gửi 4 yêu cầu nhận máy với các câu trả lời số seri khác nhau để thử vận may và gửi tin nhắn quấy rối đe dọa ép giao máy.',
    evidence: 'Log hệ thống ghi nhận 4 lần trả lời sai câu hỏi bí mật + ảnh chụp tin nhắn ép giao máy.',
    time: '15 phút trước',
    status: 'pending',
  },
  {
    id: 'REP-702',
    claimId: 'YC-402',
    itemId: 'TD-9018',
    itemName: 'Điện thoại iPhone 15 Pro Titan',
    itemImg: 'https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=300&q=80',
    reportType: 'extortion',
    typeLabel: 'Đòi tiền chuộc bất hợp pháp',
    severity: 'critical',
    reporter: 'Phạm Thu Trang (Chủ sở hữu mất đồ)',
    reportedUser: 'Nguyễn T. (Người giữ đồ)',
    reportedUserPhone: '0905 444 123',
    reportedUserId: 'USR-904',
    reason: 'Người nhặt ép chủ nhân phải chuyển khoản trước 5 triệu tiền "chuộc máy" mới trả.',
    evidence: 'Ảnh chụp màn hình tin nhắn Zalo kèm số tài khoản ngân hàng yêu cầu chuyển tiền chuộc.',
    time: '1 giờ trước',
    status: 'pending',
  },
];

export const USERS_LIST = [
  { id: 'USR-101', name: 'Nguyễn Văn An', email: 'an.nguyen@example.com', trustScore: 98, returnsCount: 5, verified: true, role: 'Thành viên Tích Cực', status: 'Hoạt động' },
  { id: 'USR-102', name: 'Trần Văn Bình', email: 'binh.tran@example.com', trustScore: 92, returnsCount: 1, verified: true, role: 'Thành viên', status: 'Hoạt động' },
  { id: 'USR-105', name: 'Tài khoản nghi vấn #882', email: 'spam_bot88@tempmail.com', trustScore: 24, returnsCount: 0, verified: false, role: 'Cảnh báo', status: 'Đã tạm khóa' },
];
